"use client";

import { useState, useEffect, useRef } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  ScrollText,
  UserCircle2,
  MapPin,
  Star,
  CreditCard,
  AlertTriangle,
  Scale,
  Globe,
  RefreshCw,
  Plane,
  Mail,
  Lock,
  ChevronRight,
  ShieldOff,
  Gavel,
  BookOpen,
} from "lucide-react";

// ─── Section icon map ─────────────────────────────────────────────────────────

const sectionIcons = {
  "acceptance":        ScrollText,
  "use-of-service":    UserCircle2,
  "itinerary-content": MapPin,
  "community":         Star,
  "payments":          CreditCard,
  "disclaimers":       AlertTriangle,
  "liability":         ShieldOff,
  "governing-law":     Gavel,
  "third-party":       Globe,
  "changes":           RefreshCw,
};

// ─── Data ────────────────────────────────────────────────────────────────────

const sections = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: [
      {
        subtitle: "Agreement to Terms",
        text: "By downloading, installing, or using Routezy (the \"App\"), you agree to be bound by these Terms and Conditions (\"Terms\"). If you do not agree to these Terms in full, you must not access or use Routezy.",
      },
      {
        subtitle: "Eligibility",
        text: "You must be at least 13 years of age to use Routezy. By using the App, you represent and warrant that you meet this requirement. If you are between 13 and 18, you confirm that a parent or legal guardian has reviewed and agreed to these Terms on your behalf.",
      },
      {
        subtitle: "Updates to Terms",
        text: "Routezy reserves the right to modify these Terms at any time. We will notify you of material changes via in-app notification or email at least 14 days before they take effect. Continued use of the App after the effective date constitutes your acceptance of the revised Terms.",
      },
    ],
  },
  {
    id: "use-of-service",
    title: "Use of Service",
    content: [
      {
        subtitle: "Permitted Use",
        text: "Routezy grants you a limited, non-exclusive, non-transferable, revocable licence to use the App for your personal, non-commercial travel planning purposes in accordance with these Terms.",
      },
      {
        subtitle: "Account Responsibility",
        text: "You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately at routezy.support@gmail.com if you suspect any unauthorised access to your account.",
      },
      {
        subtitle: "Prohibited Conduct",
        text: "You agree not to: reverse-engineer, decompile, or disassemble the App; use automated scripts or bots to access Routezy services; upload malicious code or interfere with the App's infrastructure; impersonate another user or entity; or use Routezy in any way that violates applicable laws or regulations.",
      },
      {
        subtitle: "Account Termination",
        text: "Routezy reserves the right to suspend or permanently terminate your account at its discretion if you breach these Terms, engage in fraudulent activity, or misuse the platform in a way that harms other users or the integrity of the service.",
      },
    ],
  },
  {
    id: "itinerary-content",
    title: "Itinerary & Content Accuracy",
    content: [
      {
        subtitle: "Generated Itineraries",
        text: "Itineraries generated by Routezy are produced algorithmically based on data from third-party sources including Google Places API. While we strive for accuracy, we cannot guarantee that attraction opening hours, entry fees, or availability are current or correct at the time of your visit.",
      },
      {
        subtitle: "User Responsibility",
        text: "You are solely responsible for verifying all itinerary details — including opening hours, admission requirements, and safety conditions — before visiting any location. Routezy is a planning aid, not a substitute for your own due diligence.",
      },
      {
        subtitle: "Route Optimization",
        text: "Route distances and travel time estimates are approximations based on real-time or cached data from mapping APIs. Actual travel times may differ due to traffic, road closures, weather, or other conditions outside Routezy's control.",
      },
      {
        subtitle: "Map Data",
        text: "Map data is provided by Google Maps Platform and is subject to Google's terms of service. Routezy does not own, control, or warrant the accuracy of any underlying map or location data.",
      },
    ],
  },
  {
    id: "community",
    title: "Community Features",
    content: [
      {
        subtitle: "User-Generated Content",
        text: "By submitting traveler tips, reviews, or any other content (\"User Content\") to Routezy, you grant us a worldwide, royalty-free, non-exclusive licence to use, display, reproduce, and distribute that content within the App and our marketing materials.",
      },
      {
        subtitle: "Content Standards",
        text: "You agree that your User Content will not be defamatory, misleading, obscene, hateful, or in violation of any third party's rights. Routezy reserves the right to remove any content that violates these standards without prior notice.",
      },
      {
        subtitle: "Shared Itineraries",
        text: "When you share an itinerary via a public link, that itinerary plan (not your personal account data) becomes accessible to anyone with the link. You accept full responsibility for any itinerary content you choose to share publicly.",
      },
      {
        subtitle: "Private Notes",
        text: "Private notes you create within Routezy are not shared with other users or partners and are visible only to you. Routezy employees do not access private notes except when required by law or to investigate platform abuse.",
      },
    ],
  },
  {
    id: "payments",
    title: "Affiliate & Partner Bookings",
    content: [
      {
        subtitle: "Affiliate & Partner Bookings",
        text: "Hotel, activity, and transport bookings made through Routezy redirect you to third-party platforms. All booking charges, cancellation policies, and refund rights are governed solely by those third-party providers. Routezy receives a commission but is not party to the booking contract.",
      },
    ],
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    content: [
      {
        subtitle: "As-Is Service",
        text: "Routezy is provided on an \"as is\" and \"as available\" basis without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.",
      },
      {
        subtitle: "Travel Safety",
        text: "Routezy does not assume responsibility for your personal safety during travel. You should always research local safety conditions, travel advisories, and health requirements before visiting any destination. Emergency services should be contacted directly in the event of any danger.",
      },
      {
        subtitle: "Service Availability",
        text: "We do not guarantee that Routezy will be available at all times, error-free, or free from interruptions. We may suspend access for maintenance, updates, or circumstances beyond our control without prior notice.",
      },
    ],
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    content: [
      {
        subtitle: "Exclusion of Damages",
        text: "To the maximum extent permitted by applicable law, Routezy and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the App.",
      },
      {
        subtitle: "Liability Cap",
        text: "In no event shall Routezy's total cumulative liability to you for any claims arising from these Terms or your use of the App exceed the greater of (a) the amount you paid to Routezy in the 12 months preceding the claim, or (b) INR 1,000.",
      },
      {
        subtitle: "Indemnification",
        text: "You agree to indemnify and hold harmless Routezy and its affiliates from any claims, losses, damages, liabilities, and expenses (including legal fees) arising from your breach of these Terms, your User Content, or your violation of any law or third-party rights.",
      },
    ],
  },
  {
    id: "governing-law",
    title: "Governing Law & Disputes",
    content: [
      {
        subtitle: "Jurisdiction",
        text: "These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in New Delhi, India.",
      },
      {
        subtitle: "Dispute Resolution",
        text: "Before initiating any legal proceedings, you agree to first contact Routezy at routezy.support@gmail.com and attempt to resolve the dispute informally for a period of 30 days. If the dispute cannot be resolved informally, either party may then pursue formal legal remedies.",
      },
      {
        subtitle: "Severability",
        text: "If any provision of these Terms is found to be unenforceable or invalid under applicable law, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions shall continue in full force and effect.",
      },
    ],
  },
  {
    id: "third-party",
    title: "Third-Party Services",
    content: [
      {
        subtitle: "External Links & Services",
        text: "Routezy integrates with third-party services including Google Maps Platform, Firebase, Booking.com, GetYourGuide, Ola, and Uber. Your use of these services is subject to their respective terms and privacy policies. Routezy is not responsible for the practices or content of third-party services.",
      },
      {
        subtitle: "Sponsored Content",
        text: "Sponsored placements and promoted attractions within Routezy are clearly labeled. Inclusion of a sponsored listing does not constitute an endorsement by Routezy. We are not responsible for the quality, accuracy, or safety of any sponsored establishment.",
      },
    ],
  },
  {
    id: "changes",
    title: "Changes to the App",
    content: [
      {
        subtitle: "Feature Modifications",
        text: "Routezy reserves the right to modify, suspend, or discontinue any feature or aspect of the App at any time, including free-tier features, without liability to you. We will make reasonable efforts to communicate significant changes in advance.",
      },
      {
        subtitle: "Beta Features",
        text: "Certain features may be released in beta and may not function as intended. Beta features are provided without warranty and may be removed or changed at any time without notice.",
      },
    ],
  },
];

const versionHistory = [
  { version: "1.0.0", date: "March 22, 2026", change: "Initial published policy." },
];

const trustStats = [
  { Icon: Scale,    label: "Fair & Transparent" },
  { Icon: Lock,     label: "Secure Platform" },
  { Icon: BookOpen, label: "Plain Language" },
  { Icon: Gavel,    label: "India Jurisdiction" },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function GradientText({ children }) {
  return (
    <span
      style={{
        background: "linear-gradient(135deg, #FF6B6B 0%, #FF8E53 50%, #FFC947 100%)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        backgroundClip: "text",
      }}
    >
      {children}
    </span>
  );
}

function TableOfContents({ activeSection, onNavigate }) {
  return (
    <nav className="sticky top-8 hidden lg:block">
      <div
        className="rounded-2xl p-6"
        style={{
          background: "#F8F9FC",
          border: "1px solid #E2E8F2",
          boxShadow: "0 2px 8px rgba(0,0,0,0.06), 0 8px 24px rgba(0,0,0,0.04)",
        }}
      >
        <p
          className="text-xs font-bold uppercase tracking-widest mb-5"
          style={{ color: "#6B7280", fontFamily: "'DM Sans', sans-serif" }}
        >
          Contents
        </p>
        <ul className="space-y-1">
          {sections.map((s) => {
            const Icon = sectionIcons[s.id];
            const isActive = activeSection === s.id;
            return (
              <li key={s.id}>
                <button
                  onClick={() => onNavigate(s.id)}
                  className="w-full text-left flex items-center gap-3 px-3 py-2 rounded-xl transition-all duration-200"
                  style={{
                    background: isActive
                      ? "linear-gradient(135deg, rgba(255,107,107,0.12) 0%, rgba(255,201,71,0.08) 100%)"
                      : "transparent",
                  }}
                >
                  <Icon
                    size={15}
                    strokeWidth={isActive ? 2.2 : 1.8}
                    style={{ color: isActive ? "#FF6B6B" : "#9CA3AF", flexShrink: 0 }}
                  />
                  <span
                    className="text-sm font-medium flex-1"
                    style={{
                      color: isActive ? "#FF6B6B" : "#374151",
                      fontFamily: "'DM Sans', sans-serif",
                    }}
                  >
                    {s.title}
                  </span>
                  {isActive && (
                    <ChevronRight size={13} style={{ color: "#FF6B6B", flexShrink: 0 }} />
                  )}
                </button>
              </li>
            );
          })}
        </ul>
      </div>
    </nav>
  );
}

function SectionCard({ section, index }) {
  const Icon = sectionIcons[section.id];
  return (
    <div
      id={section.id}
      className="rounded-2xl p-8 scroll-mt-8"
      style={{
        background: "#FFFFFF",
        border: "1px solid #E2E8F2",
        boxShadow: "0 2px 8px rgba(0,0,0,0.06), 0 8px 24px rgba(0,0,0,0.04)",
      }}
    >
      {/* Header */}
      <div className="flex items-start gap-4 mb-7">
        <div
          className="w-12 h-12 rounded-2xl flex items-center justify-center flex-shrink-0"
          style={{
            background: "linear-gradient(135deg, rgba(255,107,107,0.12) 0%, rgba(255,201,71,0.10) 100%)",
            border: "1px solid rgba(255,107,107,0.15)",
          }}
        >
          <Icon size={22} strokeWidth={1.8} style={{ color: "#FF6B6B" }} />
        </div>
        <div>
          <span
            className="text-xs font-bold uppercase tracking-widest"
            style={{ color: "#FF8E53", fontFamily: "'DM Sans', sans-serif" }}
          >
            Clause {String(index + 1).padStart(2, "0")}
          </span>
          <h2
            className="text-xl font-semibold mt-0.5"
            style={{ color: "#0F2044", fontFamily: "'Poppins', sans-serif" }}
          >
            {section.title}
          </h2>
        </div>
      </div>

      {/* Divider */}
      <div
        className="h-px mb-7"
        style={{ background: "linear-gradient(90deg, #FF6B6B22, #FFC94722, transparent)" }}
      />

      {/* Content */}
      <div className="space-y-6">
        {section.content.map((block, i) => (
          <div key={i} className="flex gap-4">
            <div className="flex-shrink-0 mt-2.5">
              <div
                className="w-2 h-2 rounded-full"
                style={{ background: "linear-gradient(135deg, #FF6B6B, #FFC947)" }}
              />
            </div>
            <div>
              <h3
                className="text-base font-semibold mb-1.5"
                style={{ color: "#1E3A6E", fontFamily: "'Poppins', sans-serif" }}
              >
                {block.subtitle}
              </h3>
              <p
                className="text-sm"
                style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif", lineHeight: "1.75" }}
              >
                {block.text}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function TermsAndConditionsPage() {
  const [activeSection, setActiveSection] = useState(sections[0].id);
  const observerRef = useRef(null);

  useEffect(() => {
    const link = document.createElement("link");
    link.href =
      "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&family=DM+Sans:wght@400;500;600&display=swap";
    link.rel = "stylesheet";
    document.head.appendChild(link);
  }, []);

  useEffect(() => {
    observerRef.current = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => { if (e.isIntersecting) setActiveSection(e.target.id); });
      },
      { rootMargin: "-20% 0px -60% 0px" }
    );
    sections.forEach((s) => {
      const el = document.getElementById(s.id);
      if (el) observerRef.current.observe(el);
    });
    return () => observerRef.current?.disconnect();
  }, []);

  const scrollTo = (id) =>
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });

  return (
    <div style={{ background: "#F8F9FC", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif" }}>

      {/* ── Navbar ── */}
      <header
        className="sticky top-0 z-50 backdrop-blur-md"
        style={{ background: "rgba(248,249,252,0.92)", borderBottom: "1px solid #E2E8F2" }}
      >
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src="/Logo.png"
              alt="Routezy Logo"
              width={48}
              height={48}
              className="rounded-xl"
            />
            <span className="font-bold text-lg" style={{ color: "#0F2044", fontFamily: "'Poppins', sans-serif" }}>
              Routezy
            </span>
          </Link>

          <div className="flex items-center gap-6">
            <Link
              href="/request-account-deletion"
              className="text-sm font-medium transition-colors hover:text-orange-500"
              style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif" }}
            >
              Request Account Deletion
            </Link>
            <Link
              href="/"
              className="text-sm font-medium transition-colors hover:text-orange-500"
              style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif" }}
            >
              Privacy Policy
            </Link>
          </div>
        </div>
      </header>

      {/* ── Hero ── */}
      <section className="relative overflow-hidden">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
              "radial-gradient(ellipse 80% 60% at 50% -10%, rgba(255,107,107,0.12) 0%, rgba(255,201,71,0.06) 60%, transparent 100%)",
          }}
        />
        <div
          className="absolute inset-0 pointer-events-none opacity-30"
          style={{
            backgroundImage:
              "linear-gradient(#E2E8F2 1px, transparent 1px), linear-gradient(90deg, #E2E8F2 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />

        <div className="relative max-w-4xl mx-auto px-6 pt-20 pb-16 text-center">
          {/* Badge */}
          <div
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-semibold uppercase tracking-wider mb-6"
            style={{
              background: "linear-gradient(135deg, rgba(255,107,107,0.12), rgba(255,201,71,0.08))",
              border: "1px solid rgba(255,107,107,0.2)",
              color: "#FF6B6B",
              fontFamily: "'DM Sans', sans-serif",
            }}
          >
            <ScrollText size={12} strokeWidth={2.5} />
            Last Updated: March 22, 2026 · Version 1.0.0
          </div>

          <h1
            className="text-4xl md:text-5xl lg:text-6xl font-bold mb-5 leading-tight"
            style={{ color: "#0F2044", fontFamily: "'Poppins', sans-serif" }}
          >
            Terms &amp; <GradientText>Conditions</GradientText>
          </h1>

          <p
            className="text-lg md:text-xl max-w-2xl mx-auto"
            style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif", lineHeight: "1.75" }}
          >
            These Terms govern your use of Routezy. We've written them in plain language so you know exactly
            what to expect — your rights, our responsibilities, and how we work together.
          </p>

          {/* Trust stats */}
          <div className="flex flex-wrap items-center justify-center gap-4 mt-10">
            {trustStats.map(({ Icon, label }) => (
              <div
                key={label}
                className="flex items-center gap-2.5 px-4 py-2.5 rounded-2xl"
                style={{
                  background: "#FFFFFF",
                  border: "1px solid #E2E8F2",
                  boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
                }}
              >
                <Icon size={15} strokeWidth={2} style={{ color: "#FF6B6B" }} />
                <span
                  className="text-sm font-medium"
                  style={{ color: "#1E3A6E", fontFamily: "'DM Sans', sans-serif" }}
                >
                  {label}
                </span>
              </div>
            ))}
          </div>

          {/* Agreement notice */}
          <div
            className="mt-8 mx-auto max-w-xl px-5 py-4 rounded-2xl flex items-start gap-3 text-left"
            style={{
              background: "rgba(255,201,71,0.08)",
              border: "1px solid rgba(255,201,71,0.3)",
            }}
          >
            <AlertTriangle size={16} strokeWidth={2} style={{ color: "#FF8E53", flexShrink: 0, marginTop: 2 }} />
            <p
              className="text-sm"
              style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif", lineHeight: "1.65" }}
            >
              By using Routezy, you agree to these Terms. Please read them carefully before proceeding. If you disagree with any part, you should discontinue use of the App.
            </p>
          </div>
        </div>
      </section>

      {/* ── Main ── */}
      <main className="max-w-7xl mx-auto px-6 pb-24">
        <div className="grid grid-cols-1 lg:grid-cols-[260px_1fr] gap-8 items-start">

          <TableOfContents activeSection={activeSection} onNavigate={scrollTo} />

          <div className="space-y-6">
            {sections.map((section, i) => (
              <SectionCard key={section.id} section={section} index={i} />
            ))}

            {/* Version History */}
            <div
              className="rounded-2xl p-8"
              style={{
                background: "#FFFFFF",
                border: "1px solid #E2E8F2",
                boxShadow: "0 2px 8px rgba(0,0,0,0.06), 0 8px 24px rgba(0,0,0,0.04)",
              }}
            >
              <div className="flex items-center gap-3 mb-6">
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center"
                  style={{ background: "rgba(14,165,233,0.1)", border: "1px solid rgba(14,165,233,0.2)" }}
                >
                  <BookOpen size={20} strokeWidth={1.8} style={{ color: "#0EA5E9" }} />
                </div>
                <h2
                  className="text-xl font-semibold"
                  style={{ color: "#0F2044", fontFamily: "'Poppins', sans-serif" }}
                >
                  Version History
                </h2>
              </div>
              <div className="space-y-4">
                {versionHistory.map((v, i) => (
                  <div key={i} className="flex gap-4 items-start">
                    <div
                      className="flex-shrink-0 px-2.5 py-1 rounded-lg text-xs font-bold"
                      style={{
                        background:
                          i === 0
                            ? "linear-gradient(135deg, rgba(255,107,107,0.12), rgba(255,201,71,0.10))"
                            : "rgba(226,232,242,0.6)",
                        color: i === 0 ? "#FF6B6B" : "#6B7280",
                        border: i === 0 ? "1px solid rgba(255,107,107,0.2)" : "1px solid #E2E8F2",
                        fontFamily: "'DM Sans', sans-serif",
                      }}
                    >
                      v{v.version}
                    </div>
                    <div>
                      <span
                        className="text-xs font-medium"
                        style={{ color: "#6B7280", fontFamily: "'DM Sans', sans-serif" }}
                      >
                        {v.date}
                      </span>
                      <p
                        className="text-sm mt-0.5"
                        style={{ color: "#374151", fontFamily: "'DM Sans', sans-serif" }}
                      >
                        {v.change}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Contact Card */}
            <div
              className="rounded-2xl p-8 relative overflow-hidden"
              style={{
                background: "linear-gradient(135deg, #0F2044 0%, #1E3A6E 100%)",
                boxShadow: "0 20px 60px rgba(15,32,68,0.18)",
              }}
            >
              <div
                className="absolute -top-10 -right-10 w-48 h-48 rounded-full pointer-events-none"
                style={{ background: "radial-gradient(circle, rgba(255,107,107,0.2) 0%, transparent 70%)" }}
              />
              <div
                className="absolute -bottom-8 -left-8 w-36 h-36 rounded-full pointer-events-none"
                style={{ background: "radial-gradient(circle, rgba(255,201,71,0.15) 0%, transparent 70%)" }}
              />

              <div className="relative">
                <h2
                  className="text-2xl font-bold text-white mb-2"
                  style={{ fontFamily: "'Poppins', sans-serif" }}
                >
                  Questions About These Terms?
                </h2>
                <p
                  className="text-sm mb-6"
                  style={{ color: "rgba(255,255,255,0.65)", fontFamily: "'DM Sans', sans-serif", lineHeight: "1.75" }}
                >
                  Our dedicated support team responds to all inquiries within 2 business days. For urgent
                  account-related requests, use the in-app Settings flow for the fastest resolution.
                </p>
                <div className="flex flex-wrap gap-3">
                  <a
                    href="mailto:routezy.support@gmail.com"
                    className="inline-flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-semibold"
                    style={{
                      background: "linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%)",
                      color: "#fff",
                      fontFamily: "'DM Sans', sans-serif",
                      boxShadow: "0 4px 16px rgba(255,107,107,0.4)",
                    }}
                  >
                    <Mail size={15} strokeWidth={2} />
                    routezy.support@gmail.com
                  </a>
                </div>
                <p
                  className="text-xs mt-5"
                  style={{ color: "rgba(255,255,255,0.4)", fontFamily: "'DM Sans', sans-serif" }}
                >
                  Routezy · Governed by the laws of India · © 2025 All rights reserved
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* ── Footer ── */}
      <footer style={{ borderTop: "1px solid #E2E8F2", background: "#fff" }}>
        <div className="max-w-7xl mx-auto px-6 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <Image
              src="/Logo.png"
              alt="Routezy Logo"
              width={32}
              height={32}
              className="rounded-lg"
            />
            <span
              className="text-sm font-semibold"
              style={{ color: "#0F2044", fontFamily: "'Poppins', sans-serif" }}
            >
              Routezy
            </span>
            <span className="text-sm" style={{ color: "#6B7280", fontFamily: "'DM Sans', sans-serif" }}>
              · Explore More. Waste Less Time. Travel Smart.
            </span>
          </div>
          <div className="flex items-center gap-6">
            <Link
              href="/"
              className="text-xs font-medium transition-colors hover:text-orange-400"
              style={{ color: "#6B7280", fontFamily: "'DM Sans', sans-serif" }}
            >
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}